config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'videos#index'

  resources :videos do
    resources :votes
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :video
  belongs_to :author, class_name: User

  validates :body, length: {minimum: 1}, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :videos
  has_many :votes
  has_many :comments
end

app/models/video.rb
class Video < ApplicationRecord
  has_many :comments
  has_many :votes
  belongs_to :author, class_name: User

  validates :title, length: {minimum: 1}, presence: true
  validates :url, length: {minimum: 1}, presence: true
  validates :upvotes, numericality: true, presence: true
  validates :downvotes, numericality: true, presence: true

  def upvote
    self.increment!(:upvotes, 1)
  end

  def downvote
    self.increment!(:downvotes, 1)
  end

  def net_votes
    self.upvotes - self.downvotes
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :voter, class_name: User
  belongs_to :video

  validates :value, inclusion: {in: [-1, 1]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
  end

  private

  def video_params
    params.require(:video).permit(:title, :url)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def create
    video = Video.find(params[:video_id])
    vote = video.votes.build(value: params[:value], voter_id: current_user.id)
    if vote.save!
      vote_value = params[:value].to_i
      if vote_value > 0
        video.upvote
      elsif vote_value < 0
        video.downvote
      end
    end
    redirect_to video_path(video)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cattube</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "CatTube", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
        <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
  
  <main>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>

      <%= yield %>

    </div>
  </main>

</body>
</html>

app/views/videos/index.html.erb
<ul class="video-list">
  <% @videos.each do |video| %>
    <li class="video-listing">
      <%= link_to "#{video.title} - #{video.comments.count} comments", video %>
    </li>
  <% end %>
</ul>

app/views/videos/show.html.erb
<div class="video-player">
  <%= @video.url %>
</div>

<section class="video-details">
  <h2><%= @video.title %></h2>
  <p>Posted by: <%= @video.author.email %></p>
  <% if user_signed_in? %>
    <%= button_to "Upvote", video_votes_path(@video), method: :create, params: {value: 1} %>
    <%= button_to "Downvote", video_votes_path(@video), method: :create, params: {value: -1} %>
  <% else %>
    <p>You must be logged in to vote.</p>
  <% end %>

  <p>Upvotes: <%= @video.upvotes %></p>
  <p>Downvotes: <%= @video.downvotes %></p>
  <p>Net: <%= @video.net_votes %></p>
</section>

<section class="comments">
  <h3>Comments</h3>
  <ul class="comment-list"></ul>
  <% @video.comments.each do |comment| %>
    <li class="comment-listing"><%= comment.body %> - <%= comment.author.email %></li>
  <% end %>
  </ul>
</section>